name: Deploy AgroSmart to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.4'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Flutter web
        run: |
          flutter build web \
            --release \
            --base-href "/agroSmart/" \
            --dart-define=GROQ_API_KEY=${{ secrets.GROQ_API_KEY }} \
            --dart-define=WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}

      - name: Add .nojekyll
        run: touch build/web/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages